# Generated by Django 5.0.6 on 2024-05-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ispaused_pub_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
