# Generated by Django 5.0.6 on 2024-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_name_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valoracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
