# Generated by Django 5.0.6 on 2024-05-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_valoracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='valoracion',
            new_name='rating',
        ),
    ]
