# Generated by Django 5.0.6 on 2024-05-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='desired',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
