# Generated by Django 5.0.6 on 2024-05-27 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pub_desired'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_items', models.ManyToManyField(related_name='trade_proposals', to='main.pub')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=0.000505050505050505),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pub'),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
