# Generated by Django 5.0.6 on 2024-05-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tradeproposal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeproposal',
            name='date',
        ),
    ]
