# Generated by Django 5.0.6 on 2024-05-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_tradeproposal_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeProposal',
        ),
    ]
