# Generated by Django 5.0.6 on 2024-05-31 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_photo_delete_image_remove_pub_photos_photo_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproposal',
            name='suc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sucursal'),
        ),
    ]
