# Generated by Django 5.0.6 on 2024-06-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_tradeproposal_suc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproposal',
            name='date',
            field=models.DateField(null=True, blank=True, default=None),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.tradeproposal')),
            ],
        ),
    ]
