# Generated by Django 5.0.6 on 2024-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_tradeproposal_date_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeproposal',
            name='date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
