# Generated by Django 5.0.6 on 2024-06-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_tradeproposal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeproposal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
