# Generated by Django 5.0.6 on 2024-06-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_tradeproposal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('concreted', 'Concreted'), ('no_finished', 'no_finished')], default='pending', max_length=20),
        ),
    ]
