# Generated by Django 5.0.6 on 2024-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_tradeproposal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeproposal",
            name="code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
