# Generated by Django 5.0.6 on 2024-06-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tradeproposal_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Sales',
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('concreted', 'Concreted'), ('not_finished', 'Not Finished')], default='pending', max_length=20),
        ),
    ]
