# Generated by Django 5.0.6 on 2024-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("image", models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name="AdsImage",
        ),
    ]
