# Generated by Django 5.0.6 on 2024-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproposal',
            name='proposer_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='proposer_rate_sucursal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='recipient_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='recipient_rate_sucursal',
            field=models.BooleanField(default=False),
        ),
    ]
