# Generated by Django 5.0.6 on 2024-07-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_tradeproposal_proposer_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeproposal',
            old_name='proposer_rate',
            new_name='proposer_rated',
        ),
        migrations.RenameField(
            model_name='tradeproposal',
            old_name='proposer_rate_sucursal',
            new_name='proposer_rated_sucursal',
        ),
        migrations.RenameField(
            model_name='tradeproposal',
            old_name='recipient_rate',
            new_name='recipient_rated',
        ),
        migrations.RenameField(
            model_name='tradeproposal',
            old_name='recipient_rate_sucursal',
            new_name='recipient_rated_sucursal',
        ),
    ]
