# Generated by Django 5.0.6 on 2024-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_proposer_rate_tradeproposal_proposer_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
