# Generated by Django 5.0.6 on 2024-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_user_total_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
