# Generated by Django 5.0.6 on 2024-07-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_user_total_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='main.sucursal')),
            ],
        ),
    ]
